# Generated by Django 2.2.4 on 2020-02-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200205_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Institucion'),
            preserve_default=False,
        ),
    ]
