# Generated by Django 2.2.6 on 2020-02-06 23:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_asistentescarreras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsistentesCarreras',
            new_name='AsistentesCarrera',
        ),
    ]
