# Generated by Django 2.2.6 on 2020-02-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200206_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapsoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='lapso_academico',
        ),
    ]
