# Generated by Django 2.2.6 on 2020-02-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200207_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapsoacademico',
            name='lapso',
            field=models.CharField(max_length=30),
        ),
    ]
