# Generated by Django 2.2.6 on 2020-02-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200207_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsoacademico',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lapso_academico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.LapsoAcademico'),
            preserve_default=False,
        ),
    ]
